# Generated by Django 5.0.7 on 2024-08-07 10:27

import employee_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=employee_management.models.employee_image_path),
        ),
    ]
