# Generated by Django 5.0.7 on 2024-08-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0005_alter_employee_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
