# Generated by Django 5.0.8 on 2024-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0007_employee_groups_employee_is_active_employee_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
