# Generated by Django 5.0.8 on 2024-08-16 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_alter_employee_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='department',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract')], default='fulltime', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posted_by',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualifications',
            field=models.TextField(default='BSCS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], max_length=50)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='employee_management.jobposting')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employee_management.applicant'),
            preserve_default=False,
        ),
    ]
