# Generated by Django 5.0.8 on 2024-08-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0015_rename_created_at_jobposting_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
