# Generated by Django 5.0.8 on 2024-08-16 12:01

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0021_jobposting_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='qualifications',
            field=models.TextField(default='educated'),
            preserve_default=False,
        ),
    ]
