# Generated by Django 5.0.8 on 2024-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0022_remove_jobposting_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
