# Generated by Django 5.0.8 on 2024-08-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0026_remove_jobposting_posted_by_jobposting_posted_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='posted_by_id',
            new_name='posted_by',
        ),
    ]
