# Generated by Django 5.0.8 on 2024-08-19 07:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0027_rename_posted_by_id_jobposting_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('offer_extended', 'Offer Extended'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.jobposting'),
        ),
    ]
