# Generated by Django 5.0.8 on 2024-08-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0028_remove_application_submitted_at_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
    ]
