# Generated by Django 5.0.8 on 2024-08-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0029_remove_application_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                default=44, on_delete=models.CASCADE, to="employee_management.Applicant"
            ),
        )
    ]
