# Generated by Django 5.0.8 on 2024-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0031_alter_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_made', 'Offer Made'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
    ]
