# Generated by Django 5.0.8 on 2024-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0033_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_made', 'Offer Made'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
