# Generated by Django 5.0.8 on 2024-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0036_remove_leave_approved_leave_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('half_day', 'Half Day'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('annual_leave', 'Annual Leave')], max_length=20),
        ),
    ]
