# Generated by Django 5.0.8 on 2024-08-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0037_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours_worked',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('Late', 'Late'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('half_day', 'Half Day'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('annual_leave', 'Annual Leave')], max_length=20),
        ),
    ]
