# Generated by Django 5.0.8 on 2024-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0038_attendance_hours_worked_attendance_is_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
