# Generated by Django 5.0.8 on 2024-08-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0043_leave_created_at_leave_hr_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('Late', 'Late'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('half_day', 'Half Day'), ('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('annual_leave', 'Annual Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('annual_leave', 'Annual Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave')], max_length=20),
        ),
    ]
