# Generated by Django 5.0.8 on 2024-08-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0045_task_taskcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='author',
            new_name='created_by',
        ),
    ]
