# Generated by Django 5.0.8 on 2024-08-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0047_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='employee',
        ),
    ]
